source 'https://cdn.cocoapods.org'

platform :ios, '15.0'

target 'iosApp' do
  use_frameworks!
  pod 'composeApp', :path => '../composeApp'
  pod 'MMKV', :git => 'https://github.com/Tencent/MMKV.git', :branch => 'dev_kmp'
end
